apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels belong to deployment
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels: # these labels should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
